# Nombre de la aplicación
spring.application.name=soundtrack-sync-api

# Configuración de base de datos PostgreSQL en Supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
# 'update' creará y sincronizará automáticamente las tablas en Supabase según nuestras entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor web
server.port=8080